import os
import pickle
import numpy as np
import shutil
from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from PIL import Image
import tensorflow as tf
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input

app = FastAPI()

# Enable CORS so Streamlit can communicate with FastAPI
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 1. Load the Pre-trained Deep Learning Model (Extracts 1280 features)
print("Loading TensorFlow Model in Backend...")
model = MobileNetV2(weights='imagenet', include_top=False, pooling='avg')

# 2. Load the AI Inventory Database generated by the notebook
inventory_path = "ml_inventory.pkl"
if os.path.exists(inventory_path):
    with open(inventory_path, "rb") as f:
        inventory = pickle.load(f)
    print("AI Inventory database loaded successfully!")
else:
    print(f"Error: {inventory_path} not found!")
    inventory = {"filenames": [], "embeddings": np.array([]), "metadata": []}

@app.get("/")
def home():
    return {"status": "Backend is running successfully"}

@app.post("/search")
async def search_similar_fashion(file: UploadFile = File(...)):
    try:
        # Load uploaded image and preprocess for MobileNetV2
        img = Image.open(file.file).convert('RGB').resize((224, 224))
        img_array = np.array(img)
        expanded_img_array = np.expand_dims(img_array, axis=0)
        preprocessed_img = preprocess_input(expanded_img_array)
        
        # Extract 1280 deep feature embeddings for the query image
        query_features = model.predict(preprocessed_img, verbose=0).flatten()
        query_features = query_features / np.linalg.norm(query_features)
        
        if len(inventory["embeddings"]) == 0:
            return {"success": False, "message": "Database is empty"}
            
        # Calculate Cosine Similarity against all images (1280 vs 1280)
        similarities = np.dot(inventory["embeddings"], query_features)
        
        # Get top 12 most similar products
        top_indices = np.argsort(similarities)[::-1][:12]
        
        results = []
        for idx in top_indices:
            results.append({
                "filename": inventory["filenames"][idx],
                "score": float(similarities[idx]),
                "metadata": inventory["metadata"][idx] if idx < len(inventory["metadata"]) else {}
            })
            
        return {"success": True, "results": results}
        
    except Exception as e:
        return {"success": False, "error": str(e)}

# ==================== AUTOMATED BACKEND REALTIME INDEXING ENDPOINT ====================
@app.post("/upload")
async def upload_and_index_fashion(file: UploadFile = File(...)):
    try:
        # 1. Save image safely inside the backend directory paths 
        os.makedirs("dataset", exist_ok=True)
        clean_filename = file.filename.replace(" ", "_").lower()
        backend_save_path = os.path.join("dataset", clean_filename)
        
        with open(backend_save_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
            
        # 2. Extract deep vector features using MobileNetV2 Model Structure
        img = Image.open(backend_save_path).convert('RGB').resize((224, 224))
        img_array = np.array(img)
        expanded_img_array = np.expand_dims(img_array, axis=0)
        preprocessed_img = preprocess_input(expanded_img_array)
        
        new_features = model.predict(preprocessed_img, verbose=0).flatten()
        new_features = new_features / np.linalg.norm(new_features)  # Matrix Normalization
        
        # 3. Append metadata details directly into running memory structures
        inventory["filenames"].append(clean_filename)
        
        if len(inventory["embeddings"]) == 0:
            inventory["embeddings"] = np.array([new_features])
        else:
            inventory["embeddings"] = np.vstack([inventory["embeddings"], new_features])
            
        inventory["metadata"].append({"source": "admin_upload"})
        
        # 4. Serialize updated inventory tracking file records over to disk arrays 
        with open(inventory_path, "wb") as f:
            pickle.dump(inventory, f)
            
        print(f"AI Index Vector Tracking Matrix Updated: {clean_filename}")
        return {"success": True, "message": "Product successfully indexed in AI Vector Space!"}
        
    except Exception as e:
        return {"success": False, "error": str(e)}